module.exports = {
  WAREHOUSE_STAFF: ['WAREHOUSE_STAFF', 'WAREHOUSE_MANAGER', 'ADMIN'],
  WAREHOUSE_MANAGER: ['WAREHOUSE_MANAGER', 'ADMIN'],

  EMPLOYEE_MANAGER: ['EMPLOYEE_MANAGER', 'ADMIN'],

  CUSTOMER_STAFF: ['CUSTOMER_STAFF', 'CUSTOMER_MANAGER', 'ADMIN'],
  CUSTOMER_MANAGER: ['CUSTOMER_MANAGER', 'ADMIN'],

  SALESMAN: ['SALESMAN', 'ADMIN'],
  ADMIN: ['ADMIN'],
  IS_ALL: ['WAREHOUSE_MANAGER', 'EMPLOYEE_MANAGER', 'CUSTOMER_MANAGER', 'WAREHOUSE_STAFF', 'SALESMAN', 'ADMIN'],
}